### ISSUE TITLE
No Automated Build

### ISSUE THREAD

**Issue by iSynaptic** [Blaster707/leetcode#13]
You have no automated build happen when you create a PR or merge code into master. Since you have automated tests for each of your leetcode exercises, you should have an automated build that runs all the tests every time you submit changes. The following article might give you some pointers: https://ryanharrison.co.uk/2020/04/12/kotlin-java-ci-with-github-actions.html

**Comment by Blaster707** [comment]
Issue resolved by creating build.yml, which builds the code and runs the test on every merge into master and on every PR that is submitted.  FYI, branch protection has also been enabled and 1 approval is required for all master merges now.

**Comment by iSynaptic** [comment]
Very good!
